### PR TITLE
ARIA Improvements for screen reader users

### PR DESCRIPTION
**Pull request by Flameborn**
Hello,

This is some ARIA markup to improve the Feather Wiki experience for [Screen Reader](https://en.wikipedia.org/wiki/Screen_reader) users. Almost all the elements are perfectly marked up.

The first commit allows screen readers to announce the notification text as they appear, e.g. when saving Feather Wiki back to a server.

I'd also like to add a *toolbar* role for the Pell action bar via a query selector, so that all the formatting buttons could be grouped and skipped, but I'm not sure where it would be best to do this.

Ideally, this would be great to have upstream, but given that the last commit for Pell (even for v2) was back in 2019, I am not sure how much attention it would receive among the 50+ other reported issues.

Any input is greatly appreciated.

### CODE REVIEW

**Comment by Alamantus** [comment]
At this point I'd be willing to just pull Pell out of the dependencies and into the main project the way I have with `md.js` and just put a comment in the file to reference the license and original repository so we can make whatever changes are needed for it. We'll just need to double check the license and make sure we can get it hooked up correctly once separated from the original repo.

**Comment by Flameborn** [comment]
This might be the best option. I'll make the appropriate change once it's in the FeatherWiki repo and mark this PR ready for review.

Licensewise I think we're good, as Pell is under MIT.

Thanks so much for being open about this.

**Comment by Alamantus** [comment]
Hey @Flameborn, I've moved `pell.js` to the `helpers` folder, so you can see about updating it to be better for screen readers. 👍

**Comment by Flameborn** [comment]
Hi @Alamantus,

Thank you. I marked up the action bar *div*, so everything is good to go now.

**Comment by Alamantus** [comment]
Oops, I lost track of this, and I'm going to be away from a computer for the next week! I'll make a note for myself to merge this and build a new patch once I get back.

**Comment by Flameborn** [comment]
No problem. Thank you for letting me know and for the merge of course.

**Comment by Alamantus** [comment]
Thanks again for the ARIA work!

I'll be making a new release soon, but I have some (frankly silly) things to think about first because now that I've moved Pell into the core Feather Wiki code, the Finch build is smaller than the Chickadee build, which breaks the naming convention because the WYSIWYG editor used to be larger than the markdown editor. I know this is extremely trivial, but I need to think about how I can realistically change Feather Wiki to just one build that's even smaller.

Anyway, keep an eye out on the website, the Codeberg repo, or my social media for when the next release with your ARIA fixes are available!

**Pull request merged**
